### ISSUE TITLE
Signup - Email already in use

### ISSUE THREAD

**Issue by WilsonLee2000** [GenesisWCH/Genes#24]
Upon keying in an email that has already been registered, a console error pop out instead of a toast message.

**Comment by WilsonLee2000** [comment]
For the sign up page, if the user type "abc" in one of the text field for example. The user then exit from insert mode and then go back to insert mode to continue typing, the "abc" will get automatically deleted and the user have to retype "abc" again.

**Comment by WilsonLee2000** [comment]
Also, the system is currently unable to detect if we are using NUS email or not to sign up.

**Comment by ketamethane** [comment]
All issues are cleared here.
